-- Create the properties table
CREATE TABLE properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    location TEXT NOT NULL,
    beds NUMERIC NOT NULL,
    baths NUMERIC NOT NULL,
    sqft NUMERIC NOT NULL,
    year_built NUMERIC,
    image TEXT NOT NULL,
    images TEXT[] DEFAULT '{}',
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows everyone to read properties
CREATE POLICY "Public properties are viewable by everyone" 
ON properties FOR SELECT 
TO public 
USING (true);

-- Create a policy that allows authenticated users (or anon for now if simpler) to insert/update
-- For this demo, we'll allow public to insert to make it work with the current Anon key setup easily
-- IN PRODUCTION: You would restrict this to authenticated admins only
CREATE POLICY "Public can insert properties" 
ON properties FOR INSERT 
TO public 
WITH CHECK (true);

CREATE POLICY "Public can update properties" 
ON properties FOR UPDATE 
TO public 
USING (true);

CREATE POLICY "Public can delete properties" 
ON properties FOR DELETE 
TO public 
USING (true);
