-- Create the inquiries table
CREATE TABLE inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    property_title TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'New', -- New, Read, Replied
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- Allow public access for demo purposes (In production, restricts to admins)
CREATE POLICY "Public can view inquiries" 
ON inquiries FOR SELECT TO public USING (true);

CREATE POLICY "Public can insert inquiries" 
ON inquiries FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Public can update inquiries" 
ON inquiries FOR UPDATE TO public USING (true);

CREATE POLICY "Public can delete inquiries" 
ON inquiries FOR DELETE TO public USING (true);

-- Insert Seed Data
INSERT INTO inquiries (name, email, property_title, message, status, created_at)
VALUES 
('John Doe', 'john@example.com', 'Modern Glass Villa', 'Is this property still available for viewing this weekend?', 'New', NOW() - INTERVAL '2 hours'),
('Alice Smith', 'alice@test.com', 'ahemdabad', 'Interested in the commercial space options.', 'Read', NOW() - INTERVAL '1 day'),
('Bob Johnson', 'bob@gmail.com', 'Seaside Retreat', 'What is the exact square footage of the backyard?', 'Replied', NOW() - INTERVAL '3 days');
